### ISSUE TITLE
Makefile.PL should not be in git

### ISSUE THREAD

**Issue by szabgab** [Htbaa/Validation-Class#3]
As I was reporting #2 I noticed this repo has both `dist.ini` and `Makefile.PL` which was generated by `dzil`. This was confusing and in usually generated files should not be include in git.

**Comment by awncorp** [comment]
Fwiw, this was intentional for two main reasons (among others), e.g.

* Collaborators needing to change dependencies, authorship, etc, can't do that without `dist.ini`
* Including `Makefile.PL`, and `META.*` files, and others, allows users to install the distribution directly from GitHub (w/o CPAN)

The `META*` files not being included was a mistake (but I'm no longer the maintainer).

**Comment by Htbaa** [comment]
I've added the `[MetaResources]` to `dist.ini` as @szabgab suggested in #2. Does that fix including the `META*` files?

@awncorp reasons seem good enough to me. But it looks to me that the `dist.ini` has been setup 10 years ago, so maybe things have changed. It's not a module that has lots of collaborators working on it though.

@szabgab would deleting `Makefile.PL` and adding it to `.gitignore` be sufficient?

**Comment by szabgab** [comment]
I am not sure, but I think doing what you suggested will improve things. We'll see then.

**Comment by Htbaa** [comment]
Reading briandfoy's reaction (https://www.reddit.com/r/perl/comments/13ib46n/comment/jke2231/) on the subject of leaving out `Makefile.PL` from the Git repository made me decide to keep it in. At least for now. To be honest I'm struggling with Dist::Zilla myself as well. This module is on maintenance mode anyway, so if having the `Makefile.PL` helps anyone to contribute a patch I'd rather keep it.
